# Generated by Django 6.0 on 2026-03-04 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_hospitalprofile_date_of_registration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
