# Generated by Django 6.0 on 2026-03-06 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctor',
            new_name='DoctorProfile',
        ),
    ]
