# Generated by Django 6.0 on 2026-03-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_doctor_doctorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='license',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
