# Generated by Django 6.0 on 2026-03-09 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='reason',
            new_name='reason_for_visit',
        ),
    ]
